//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackFilm
    {
        public int ID { get; set; }
        public int FilmID { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Rating { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
