//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public int RoomID { get; set; }
    
        public virtual Room Room { get; set; }
        public Seats(int number, int roomID)
        {
            Number = number;
            RoomID = roomID;

        }
        public Seats() { }
    }
}
