//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public int SeatNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Session Session { get; set; }
        public Ticket(int sessionID, int? accountID, int seatNumber)
        {
            SessionID = sessionID;
            AccountID = accountID;
            SeatNumber = seatNumber;
        }
    }
}
